<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>VolumeGeneratorApp.Program</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Aspose.Total.NET 5.lic" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Aspose.Total.NET 5.lic">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspose.Words" Version="25.11.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VolumeGenerator\VolumeGenerator.csproj" />
  </ItemGroup>

</Project>